4 rasberry pi wifi upload script
DallasFormulaRacing/PowertrainLib pull request #16
Opened 2024-01-29 19:42 UTC by GHAFHA

2024-01-30 19:20 UTC, Squidtoon99 commented on mongo_client/mongo_client.py
> +            print("Pinged your deployment. You successfully connected to MongoDB!")
We should implement proper logging but this should be fine for now

2024-01-30 19:21 UTC, GHAFHA commented on mongo_client/mongo_client.py
> +            print("Pinged your deployment. You successfully connected to MongoDB!")
yea we can use logging, i was gonna have vasu implement it

2024-01-30 19:27 UTC, Squidtoon99 requested changes
I think that we don't need an abstraction layer on top of the python MongoClient, we should instantiate a client, verify the connection is successful, and then return the same client.

2024-01-30 19:27 UTC, Squidtoon99 commented on mongo_client/mongo_client.py
> +            inserted_ids = collection.insert_many(data).inserted_ids
Why is this called insert document when we call insert many in the backend? This function screws with type checking and should be taking in named arguments too.

2024-01-30 19:27 UTC, Squidtoon99 commented on tests/conftest.py
> +uri = f"mongodb+srv://noel:${os.getenv('MONGO_PASSWORD')}@cluster0.gw7z3sn.mongodb.net/?retryWrites=true&w=majority"
Noooooo don't do this. ENV variable *can* be the entire variable

2024-01-30 19:27 UTC, Squidtoon99 commented on tests/conftest.py
>          file_path="/Users/noeljohnson/Documents/file.txt",
I get that this is testing but this should be a relative not absolute path

2024-01-30 19:33 UTC, GHAFHA commented on tests/conftest.py
> +uri = f"mongodb+srv://noel:${os.getenv('MONGO_PASSWORD')}@cluster0.gw7z3sn.mongodb.net/?retryWrites=true&w=majority"
i was lazy

2024-01-30 19:34 UTC, GHAFHA commented on mongo_client/mongo_client.py
> +            inserted_ids = collection.insert_many(data).inserted_ids
i think we should have an abstraction layer on top of it no? keep it object oriented, mongo_client should be called in handler, and its methods used, we can also verify the methods work as intended with way using pytest

2024-01-30 19:35 UTC, GHAFHA commented on tests/conftest.py
>          file_path="/Users/noeljohnson/Documents/file.txt",
again lazy

2024-01-30 19:36 UTC, GHAFHA commented on mongo_client/mongo_client.py
> +            inserted_ids = collection.insert_many(data).inserted_ids
i dont think renaming it is hard, i asked vasu to make the method more suitable as well as test

2024-01-30 19:40 UTC, GHAFHA commented on mongo_client/mongo_client.py
> +            inserted_ids = collection.insert_many(data).inserted_ids
and also if we're going to use logging id wanna keep the abstraction layer, keeps handler cleaner

2024-01-31 07:47 UTC, GHAFHA commented
tasks to be done before closing pull request:
- [ ] Refactor box client code
- [ ] remove network code
- [ ] implement a proper handler
- [ ] figure out ssid, device_id, off pi, as well as the name of the network in the shop for the wifi-cliend, and the password for the network
- [ ] piece together handler with the correct information

2024-02-11 01:03 UTC, merged